### ISSUE TITLE
pcaMethods

### ISSUE THREAD

**Issue by PhilipPallmann** [kwstat/agridat#4]
I find it a bit odd that agridat imports a package (pcaMethods) that is not available from CRAN. I realized this when my students failed to do their homework (analyzing a data example from agridat) because they weren't able to install the package as they didn't figure out that they had to download pcaMethods from Bioconductor. If this import is really necessary, I think it could be helpful to point it out explicitly.

Apart from this, great package! Keep it up!

Philip

**Comment by kwstat** [comment]
Thanks for the feedback and sorry for the confusion.  I've removed the dependence on pcaMethods from Bioconductor.  The agridat package now includes its own nipals() function for computing principal components in the presence of missing data (instead of using the pcaMethods package).  Uploaded to CRAN 3 Mar 2015.
